server:
  port: 8105

security:
  oauth2:
    client:
      clientId: resource-a-service
      clientSecret: password
      grant-type: client_credentials
      scope: server
      access-token-uri: http://127.0.0.1:8103/oauth/token
      user-authorization-uri: http://127.0.0.1:8103/oauth/authorize
    resource:
      user-info-uri: http://localhost:8103/user
    authorization:
      check-token-access: http://127.0.0.1:8103/oauth/check_token

spring:
  main:
    allow-bean-definition-overriding: true

