server:
  port: 8105

security:
  oauth2:
    client:
      clientId: resource-b-service
      clientSecret: password
      access-token-uri: http://127.0.0.1:8103/oauth/token
      grant-type: client_credentials
      scope: server
    resource:
      user-info-uri: http://localhost:8103/user

